-- 1번
-- 영어영문학과(002) 학생들의 학번과 이름, 입학년도 조회
-- 입학 년도 빠른 순으로 표시
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2번
-- 이름이 세 글자가 아닌 교수의 이름과 주민번호 찾기
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번
-- 남자 교수들의 이름과 나이를 나이 오름차순으로 조회
SELECT PROFESSOR_NAME 교수이름, 
--			 TO_NUMBER(2024) - TO_NUMBER(19||SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
			 MONTHS_BETWEEN( TO_DATE(SYSDATE, 'YYYYMM'), 
			 								 TO_DATE(TO_NUMBER(19||SUBSTR(PROFESSOR_SSN, 1, 4)), 'YYYYMM') ) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;

-- 4번
-- 교수 이름 성 빼고 조회
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

-- 5번
-- 재수생 입학자 조회. (입학 19살에 하면 재수아님)
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
		- TO_NUMBER(19||SUBSTR(STUDENT_SSN, 1, 2)) > 19;


-- 6번
-- 2000년도 이후 입학자들은 학번이 A로 시작하는데 
-- 2000년도 이전 학번 받은 학생들의 학번과 이름 조회하기
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO NOT LIKE 'A%';

-- 7번
-- 학번이 A517178인 한아름 학생의 학점 총 평점 구하기
-- 점수는 반올림하여 소수점 한자리까지 표시
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


